### ISSUE TITLE
[BUG] 2.5.5 broke semver

### ISSUE THREAD

**Issue by mj1856** [microsoft/ApplicationInsights-JS#1293]
In [the release notes for 2.5.5](https://github.com/microsoft/ApplicationInsights-JS/blob/master/RELEASES.md#255) it says:

> Updated React plugin to v3.0.0

This appears to be a semver violation, and broke our builds.  We had been using 2.3.0, with our `package.json` having:

```
"@microsoft/applicationinsights-react-js": "^2.3.0",
"@microsoft/applicationinsights-web": "^2.3.0"
```

Thus, `npm install` now gives version 2.5.4 of `applicationinsights-react-js` and version 2.5.5 of `applicationinsights-web`.

Since it expects 3.0.0 of `applicationinsights-react-js`, we are now failing with

> TS2322: Type 'ReactPlugin' is not assignable to type 'ITelemetryPlugin'

The error appears similar to #1032, but in this case the version mismatch is apparently by design.

**Comment by mj1856** [comment]
We have pinned both to `2.5.4` to workaround this for now, but please fix.  Thanks.

**Comment by mj1856** [comment]
Or should we have only installed `"@microsoft/applicationinsights-react-js"`?  The docs are not clear on this point.

**Comment by markwolff** [comment]
The react package is a plugin, and so you should be able to use `3.0.0` with the latest version of the SDK. I'm not sure about the TS error you are seeing, afaik the interfaces weren't changed at all. The only "breaking" change was that it uses the latest versions of react and typescript. 

https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-react-js#basic-usage

**Comment by mj1856** [comment]
It happens at compile time, if you've previously installed versions of both packages with carat syntax, such as I showed with `"^2.3.0"`, and if you aren't checking in a package lock file.  This is the case with our CI pipeline.  As CI compiles the typescript, it follows semver and grabs the latest 2.x of 2.5.5 of applicationinsights-web, and 2.5.4 of applicationinsights-react-js.  And therein lies the problem, as 2.5.5 of applicationinsights-web is now *expecting* 3.0.0 of applicationinsights-react-js to be installed.

Sure, we can upgrade, but I'm pointing out that anyone who previously installed both packages with `^2.x.x` is going to run into this.

**Comment by MSNev** [comment]
This statement is actually the wrong way around "2.5.5 of applicationinsights-web is now expecting 3.0.0 of applicationinsights-react-js".

It should be that applicationinsights-react-js v3.0.0 is expecting v2.5.5 of applicationinsights-web, where is no dependencies in ai-web for the ai-react plugin...

Apart from the listed changes for the react plugin (updated to TS 3.x and added react-hooks support), v 2.5.4 of the react plugin should work with v2.5.5 of the ai-web module...

I'm not sure I'm understanding the exact issue there are no references in the package.json definitions for v3 of the ai-react plugin (except in the ai-react plugin to define this as v3).

Looking @ #1032 the issue was resolved by just reinstalling the modules (I assume this included deleting all node_modules folders to remove old stale references) -- can you try this?

**Comment by mj1856** [comment]
You can reproduce the problem with the following steps:

1. `npx create-react-app my-app --template typescript`
2. `cd my-app`
3. `npm install @microsoft/applicationinsights-web@2.3.0`
4. `npm install @microsoft/applicationinsights-react-js@2.3.0`
5. Add a file `src/TelemetryService.tsx` with the following contents:
    ```tsx
    import { ApplicationInsights } from '@microsoft/applicationinsights-web';
    import { ReactPlugin } from '@microsoft/applicationinsights-react-js';

    class TelemetryService {

        reactPlugin: ReactPlugin;
        appInsights!: ApplicationInsights;

        constructor()
        {
            this.reactPlugin = new ReactPlugin();
        }

        async initialize(reactPluginConfig: any)
        {
            this.appInsights = new ApplicationInsights({
            config: {
                instrumentationKey: "...our key...",
                extensions: [this.reactPlugin],
                extensionConfig: {
                    [this.reactPlugin.identifier]: reactPluginConfig
                }
            }
            });
            this.appInsights.loadAppInsights();
        }
    }

    export let ai = new TelemetryService();
    ```
6. `npm run build` - It compiles without error.
7. Update to latest packages: `npm update`
8. `npm run build` - It errors with:

```
Failed to compile.

C:/dev/my-app/src/TelemetryService.tsx
TypeScript error in C:/dev/my-app/src/TelemetryService.tsx(19,30):
Type 'ReactPlugin' is not assignable to type 'ITelemetryPlugin'.
  Types of property 'processTelemetry' are incompatible.
    Type '(event: ITelemetryItem, itemCtx?: IProcessTelemetryContext | undefined) => void' is not assignable to type '(env: ITelemetryItem, itemCtx?: IProcessTelemetryContext | undefined) => void'.
      Types of parameters 'itemCtx' and 'itemCtx' are incompatible.
        Type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext | undefined' is not assignable to type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext | undefined'.
          Type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext' is not assignable to type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext'.
            The types of 'core().config.extensions' are incompatible between these types.
              Type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin[] | undefined' is not assignable to type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin[] | undefined'.
                Type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin[]' is not assignable to type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin[]'.
                  Type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin' is not assignable to type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin'.
                    Types of property 'processTelemetry' are incompatible.
                      Type '(env: import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryItem").ITelemetryItem, itemCtx?: import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsi...' is not assignable to type '(env: import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryItem").ITelemetryItem, itemCtx?: import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext ...'.
                        Types of parameters 'itemCtx' and 'itemCtx' are incompatible.
                          Type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext | undefined' is not assignable to type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext | undefined'.
                            Type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext' is not assignable to type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext'.
                              The types of 'core().config.extensions' are incompatible between these types.
                                Type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin[] | undefined' is not assignable to type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin[] | undefined'.
                                  Type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin[]' is not assignable to type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin[]'.
                                    Type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin' is not assignable to type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin'.
                                      Types of property 'setNextPlugin' are incompatible.
                                        Type '((next: import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin | import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPluginChain").ITelemetryPluginChain) => void)...' is not assignable to type '((next: import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin | import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsight...'.
                                          Type '(next: import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin | import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPluginChain").ITelemetryPluginChain) => void' is not assignable to type '(next: import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin | import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights...'.
                                            Types of parameters 'next' and 'next' are incompatible.
                                              Type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin | import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-j...' is not assignable to type 'import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin | import("C:/dev/my-app/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPluginChain").ITelemetryPluginChain'.
                                                Type 'ITelemetryPlugin' is not assignable to type 'ITelemetryPlugin | ITelemetryPluginChain'.  TS2322

    17 |             config: {
    18 |                 instrumentationKey: "...our key...",
  > 19 |                 extensions: [this.reactPlugin],
       |                              ^
    20 |                 extensionConfig: {
    21 |                     [this.reactPlugin.identifier]: reactPluginConfig
    22 |                 }
```

**Comment by MSNev** [comment]
After some investigation this looks like an issue with the signatures of the setNextPlugin() as we broke the react plugin out as a separate build (to use a later version of typescript) the TS matching of the signature is no longer auto resolving.

As a workaround you should be able to (cast) the reactPlugin to ITelemetryPlugin to avoid the TS break as during execution everything works fine.
extensions: [this.reactPlugin as ITelemetryPlugin]

**Comment by MSNev** [comment]
I started "fixing" the possible this issue in the ReactNativePlugin and started re-reviewing the description here, only to see that this is the React plugin.

We didn't add the BaseTelemetryPlugin (the change that changed the signature of setNextPlugin() to setNextPlugin: (next: ITelemetryPlugin | ITelemetryPluginChain) => void;) until v2.4.0. And the ReactPlugin was also updated at the same time to match the signature (by extending from the new BaseTelemetryPlugin() class -- to avoid this issue)

As such, I'm going to close this issue as it seems to be a version mismatch in your project where you are attempting to mix versions of the code prior to v 2.4.0 with modules post 2.4.0, the workaround above I believe is still a valid option -- even for the mixed version scenario.

**Comment by abbodh** [comment]
"@microsoft/applicationinsights-web": "2.5.5",
    "@microsoft/applicationinsights-react-js": "3.0.0",

I am still getting the error even the versions are expected as per suggestion. 

`TypeScript error in D:/home/site/repository/Source/Microsoft.Teams.Apps.SubmitIdea/ClientApp/src/helpers/app-insights.ts(17,30):
  Type 'ReactPlugin' is not assignable to type 'ITelemetryPlugin'.
    Types of property 'processTelemetry' are incompatible.
      Type '(event: ITelemetryItem, itemCtx?: IProcessTelemetryContext | undefined) => void' is not assignable to type '(env: ITelemetryItem, itemCtx?: IProcessTelemetryContext | undefined) => void'.
        Types of parameters 'itemCtx' and 'itemCtx' are incompatible.
          Type 'import("D:/home/site/repository/Source/Microsoft.Teams.Apps.SubmitIdea/ClientApp/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext | undefined' is not assignable to type 'import("D:/home/site/repository/Source/Microsoft.Teams.Apps.SubmitIdea/ClientApp/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext | undefined'.
            Type 'import("D:/home/site/repository/Source/Microsoft.Teams.Apps.SubmitIdea/ClientApp/node_modules/@microsoft/applicationinsights-web/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext' is not assignable to type 'import("D:/home/site/repository/Source/Microsoft.Teams.Apps.SubmitIdea/ClientApp/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/IProcessTelemetryContext").IProcessTelemetryContext'.
              The types returned by 'core()' are incompatible between these types.
                Type 'IAppInsightsCore' is missing the following properties from type 'IAppInsightsCore': getNotifyMgr, getPerfMgr, setPerfMgr  TS2322

      15 |             config: {
      16 |                 instrumentationKey: telemetry,
    > 17 |                 extensions: [reactPlugin],
         |                              ^
      18 |                 extensionConfig: {
      19 |                     [reactPlugin.identifier]: { history: browserHistory }
      20 |                 }
  `

**Comment by MSNev** [comment]
I believe that I addressed this as part of the 2.5.7 release.
Simplistically, rather than the react and react native releases using the previous build number for the dependency, I split the publishing into 2 steps (release core, then release react/reactnative with updates to use the just release core)

So react 3.0.2 uses 2.5.7
